services:
  db:
    image: postgres:16-alpine
    container_name: zorvyn_db
    restart: always
    environment:
      POSTGRES_DB: zorvyn_assignment
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d zorvyn_assignment"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: zorvyn_web
    restart: always
    depends_on:
      db:
        condition: service_healthy
    environment:
      SECRET_KEY: ${SECRET_KEY:-dev-only-change-me-at-least-32-characters-long}
      DATABASE_URL: ${DATABASE_URL:-postgresql://postgres:postgres@db:5432/zorvyn_assignment}
      DEBUG: ${DEBUG:-False}
      ALLOWED_HOSTS: ${ALLOWED_HOSTS:-localhost,127.0.0.1}
      CORS_ALLOWED_ORIGINS: ${CORS_ALLOWED_ORIGINS:-http://localhost:3000,http://127.0.0.1:3000}
      JWT_ACCESS_TOKEN_LIFETIME_MINUTES: ${JWT_ACCESS_TOKEN_LIFETIME_MINUTES:-15}
      JWT_REFRESH_TOKEN_LIFETIME_DAYS: ${JWT_REFRESH_TOKEN_LIFETIME_DAYS:-7}
      DJANGO_LOG_LEVEL: ${DJANGO_LOG_LEVEL:-WARNING}
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    command: >
          sh -c "python manage.py migrate &&
            python manage.py collectstatic --noinput &&
             gunicorn zorvyn_assignment.wsgi:application --bind 0.0.0.0:8000 --workers 3"

volumes:
  postgres_data:
