# Generated by Django 6.0.3 on 2026-04-02 18:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('type', models.CharField(choices=[('INCOME', 'Income'), ('EXPENSE', 'Expense')], db_index=True, max_length=10)),
                ('category', models.CharField(choices=[('SALARY', 'Salary'), ('FREELANCE', 'Freelance'), ('INVESTMENT', 'Investment'), ('BUSINESS', 'Business'), ('RENTAL', 'Rental Income'), ('OTHER_INCOME', 'Other Income'), ('FOOD', 'Food & Dining'), ('TRANSPORT', 'Transport'), ('UTILITIES', 'Utilities'), ('HEALTH', 'Health & Medical'), ('EDUCATION', 'Education'), ('ENTERTAINMENT', 'Entertainment'), ('SHOPPING', 'Shopping'), ('RENT', 'Rent'), ('TAX', 'Tax'), ('OTHER_EXPENSE', 'Other Expense')], db_index=True, max_length=20)),
                ('date', models.DateField(db_index=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'financial_record',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
