# Generated by Django 6.0.3 on 2026-04-01 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_records', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialrecord',
            name='category',
            field=models.CharField(choices=[('SALARY', 'Salary'), ('FREELANCE', 'Freelance'), ('INVESTMENT', 'Investment'), ('BUSINESS', 'Business'), ('RENTAL', 'Rental Income'), ('OTHER_INCOME', 'Other Income'), ('FOOD', 'Food & Dining'), ('TRANSPORT', 'Transport'), ('UTILITIES', 'Utilities'), ('HEALTH', 'Health & Medical'), ('EDUCATION', 'Education'), ('ENTERTAINMENT', 'Entertainment'), ('SHOPPING', 'Shopping'), ('RENT', 'Rent'), ('TAX', 'Tax'), ('OTHER_EXPENSE', 'Other Expense')], max_length=20),
        ),
    ]
