# Generated by Django 6.0.3 on 2026-04-01 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_records', '0002_alter_financialrecord_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialrecord',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financialrecord',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
